// Account/customer API surface. Implementations remain in legacy during the
// incremental split, but React screens can depend on this stable domain module.

export type {
  AccountContactPayload,
  AccountInfoUpdatePayload,
  AccountMutationResponse,
  CompanyCreateResponse,
  CompanyManagementBlocker,
  CompanyManagementCompany,
  CompanyManagementData,
  CompanyManagementDepartment,
  CompanyManagementSalesman,
  CompanyManageResponse,
  CustomerAccountContact,
  CustomerAccountManagementConfig,
  CustomerAccountSummary,
  CustomerAttachmentItem,
  CustomerAttachments,
  CustomerCompanyOption,
  CustomerCreatePayload,
  CustomerCreateResponse,
  CustomerDeleteResponse,
  CustomerDepartmentOption,
  CustomerDetailData,
  CustomerDeliveryRecord,
  CustomerEditPayload,
  CustomerEditResponse,
  CustomerItem,
  CustomerOperationalMetrics,
  CustomerOperationalRecords,
  CustomerQuoteRecord,
  CustomerRowMode,
  CustomerServiceRecord,
  CustomersData,
  DepartmentCreateResponse,
  DepartmentManageResponse,
} from './legacy';

export {
  createCompany,
  createCustomer,
  createDepartment,
  deleteCompanyRecord,
  deleteCustomer,
  deleteDepartmentRecord,
  loadAccountDetailData,
  loadCompanyManagementData,
  loadCustomerDetailData,
  loadCustomersData,
  saveAccountContact,
  updateAccountInfo,
  updateCompany,
  updateCustomer,
  updateDepartment,
} from './legacy';
