// AI workspace and account intelligence API surface.

export type {
  AiDepartmentRunResponse,
  AiPainpointVerifyResponse,
  AIWorkspaceAction,
  AIWorkspaceActionDraftResponse,
  AIWorkspaceActionEvidence,
  AIWorkspaceActionFeedback,
  AIWorkspaceActionFeedbackResponse,
  AIWorkspaceActionKind,
  AIWorkspaceAnalysis,
  AIWorkspaceDailyBrief,
  AIWorkspaceData,
  AIWorkspaceDepartment,
  AIWorkspaceDepartmentQuestionResponse,
  AIWorkspaceDraftType,
  AIWorkspaceFeaturedDepartment,
  AIWorkspaceFeedbackHistory,
  AIWorkspaceFeedbackHistoryItem,
  AIWorkspaceFeedbackKindSummary,
  AIWorkspaceFollowupTarget,
  AIWorkspaceLoadParams,
  AIWorkspaceMemoriesData,
  AIWorkspaceMemoryFilters,
  AIWorkspaceMemoryItem,
  AIWorkspaceMemoryPayload,
  AIWorkspaceMemoryResponse,
  AIWorkspaceMemoryType,
  AIWorkspacePainpoint,
  AIWorkspacePromptTarget,
  AIWorkspaceQuestionAnswer,
  AIWorkspaceQuestionFeedbackPayload,
  AIWorkspaceQuestionFeedbackRating,
  AIWorkspaceQuestionFeedbackResponse,
  AIWorkspaceQuestionHistory,
  AIWorkspaceQuestionLog,
  AIWorkspaceQuestionLogDeleteResponse,
  AIWorkspaceQuestionLogDetailData,
  AIWorkspaceQuestionModel,
  AIWorkspaceQuestionModelChoice,
  AIWorkspaceQuestionScope,
  CustomerAiDeliveryItem,
  CustomerAiDepartment,
  CustomerAiMeetingInsight,
  CustomerAiMissingInfo,
  CustomerAiNextAction,
  CustomerAiPainpoint,
  CustomerAiPainpointEvidence,
  CustomerAiProductStat,
  CustomerAiQuoteDelivery,
  CustomerAiQuoteInsights,
  CustomerAiRecentDelivery,
  CustomerAiRecommendedQuestion,
  CustomerAiVerificationInsight,
  ScheduleAICoach,
  ScheduleAICoachResponse,
} from './legacy';

export {
  askAIWorkspaceDepartmentQuestion,
  deleteAIWorkspaceQuestionLog,
  generateAIWorkspaceActionDraft,
  generateScheduleAICoach,
  loadAIWorkspaceData,
  loadAIWorkspaceMemories,
  loadAIWorkspaceQuestionLogDetailData,
  normalizeCustomerAiDepartment,
  runAiDepartmentAnalysis,
  saveAIWorkspaceMemory,
  submitAIWorkspaceActionFeedback,
  submitAIWorkspaceQuestionFeedback,
  toggleAIWorkspaceMemory,
  updateAIWorkspaceMemory,
  verifyAiPainpoint,
} from './legacy';
