# Generated by Django 5.2.3 on 2026-02-18 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0085_migrate_meeting_content_to_situation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDepartmentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_data', models.JSONField(blank=True, help_text='PainPoint, 요약, 시그널, CRM 추천 등 전체 분석 JSON', null=True, verbose_name='AI 분석 결과')),
                ('quote_delivery_data', models.JSONField(blank=True, help_text='견적→납품 전환율, 납품 주기, 제품 패턴 등', null=True, verbose_name='견적/납품 분석 결과')),
                ('meeting_count', models.IntegerField(default=0, verbose_name='분석된 미팅 수')),
                ('quote_count', models.IntegerField(default=0, verbose_name='분석된 견적 수')),
                ('delivery_count', models.IntegerField(default=0, verbose_name='분석된 납품 수')),
                ('analysis_period_start', models.DateField(blank=True, null=True, verbose_name='분석 기간 시작')),
                ('analysis_period_end', models.DateField(blank=True, null=True, verbose_name='분석 기간 종료')),
                ('token_usage', models.IntegerField(default=0, verbose_name='토큰 사용량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='reporting.department', verbose_name='분석 대상 부서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='분석 요청자')),
            ],
            options={
                'verbose_name': 'AI 부서 분석',
                'verbose_name_plural': 'AI 부서 분석 목록',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='PainPointCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('budget', '예산/가격'), ('purchase_process', '결재/구매 프로세스'), ('switching_cost', '전환 비용/재고 고착'), ('performance', '성능/정확도'), ('compatibility', '호환성/사용성'), ('delivery', '납기/재고'), ('trust', '신뢰/리스크'), ('priority', '우선순위/관심')], max_length=30, verbose_name='카테고리')),
                ('hypothesis', models.TextField(verbose_name='가설 (한 줄)')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('med', 'Med'), ('low', 'Low')], max_length=5, verbose_name='확신도')),
                ('confidence_score', models.IntegerField(default=50, verbose_name='확신도 점수 (0-100)')),
                ('evidence', models.JSONField(help_text='[{"type": "quote|fact|guess", "text": "...", "source_section": "..."}]', verbose_name='근거 (Evidence)')),
                ('attribution', models.CharField(choices=[('individual', '개인(연구원)'), ('lab', '랩'), ('purchase_route', '구매루트(거래처)'), ('institution', '기관')], max_length=20, verbose_name='귀속')),
                ('verification_question', models.TextField(verbose_name='검증 질문')),
                ('action_if_yes', models.TextField(verbose_name='맞으면 (대응 패키지)')),
                ('action_if_no', models.TextField(verbose_name='아니면 (다음 단계)')),
                ('caution', models.TextField(blank=True, verbose_name='주의 문장')),
                ('verification_status', models.CharField(choices=[('unverified', '미검증'), ('confirmed', '확인됨'), ('denied', '부정됨')], default='unverified', max_length=15, verbose_name='검증 상태')),
                ('verification_note', models.TextField(blank=True, verbose_name='검증 메모')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='검증일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painpoint_cards', to='ai_chat.aidepartmentanalysis', verbose_name='부서 분석')),
            ],
            options={
                'verbose_name': 'PainPoint 카드',
                'verbose_name_plural': 'PainPoint 카드 목록',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
    ]
