# Generated by Django 5.2.3 on 2026-04-22 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
        ('reporting', '0088_add_followup_pipeline_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFollowUpAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_data', models.JSONField(blank=True, help_text='customer_summary, key_painpoints, next_best_actions, risk_factors, deal_probability 등', null=True, verbose_name='AI 분석 결과')),
                ('meeting_count', models.IntegerField(default=0, verbose_name='분석된 미팅 수')),
                ('token_usage', models.IntegerField(default=0, verbose_name='토큰 사용량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='reporting.followup', verbose_name='분석 대상 고객')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='분석 요청자')),
            ],
            options={
                'verbose_name': 'AI 고객 분석',
                'verbose_name_plural': 'AI 고객 분석 목록',
                'ordering': ['-updated_at'],
                'unique_together': {('followup', 'user')},
            },
        ),
    ]
