# Generated by Django 5.2.3 on 2025-06-16 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='고객명')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='회사명')),
                ('status', models.CharField(choices=[('active', '진행중'), ('completed', '완료'), ('paused', '일시중지')], default='active', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=20, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '팔로우업',
                'verbose_name_plural': '팔로우업 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='방문 날짜')),
                ('visit_time', models.TimeField(verbose_name='방문 시간')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='장소')),
                ('status', models.CharField(choices=[('scheduled', '예정됨'), ('completed', '완료됨'), ('cancelled', '취소됨')], default='scheduled', max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reporting.followup', verbose_name='관련 팔로우업')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정 목록',
                'ordering': ['visit_date', 'visit_time'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created_followup', '팔로우업 생성'), ('updated_followup', '팔로우업 수정'), ('status_changed_followup', '팔로우업 상태 변경'), ('created_schedule', '일정 생성'), ('updated_schedule', '일정 수정'), ('status_changed_schedule', '일정 상태 변경'), ('note', '단순 메모')], max_length=50, verbose_name='활동 유형')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='활동 시간')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reporting.followup', verbose_name='관련 팔로우업')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='활동 사용자')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='reporting.schedule', verbose_name='관련 일정')),
            ],
            options={
                'verbose_name': '활동 히스토리',
                'verbose_name_plural': '활동 히스토리 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
