# Generated by Django 5.2.3 on 2025-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='followup',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='부서/연구실명'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업체/학교명'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='고객명'),
        ),
    ]
