# Generated by Django 5.2.3 on 2025-06-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_followup_address_followup_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='상세 내용'),
        ),
    ]
