# Generated by Django 5.2.3 on 2025-06-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_followup_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='새로운 값'),
        ),
        migrations.AddField(
            model_name='history',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='이전 값'),
        ),
        migrations.AlterField(
            model_name='history',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reporting.followup', verbose_name='관련 팔로우업'),
        ),
    ]
