# Generated by Django 5.2.3 on 2025-06-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_history_new_value_history_old_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('created_followup', '팔로우업 생성'), ('updated_followup', '팔로우업 수정'), ('created_schedule', '일정 생성'), ('updated_schedule', '일정 수정')], max_length=50, verbose_name='활동 유형'),
        ),
        migrations.AlterField(
            model_name='history',
            name='followup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reporting.followup', verbose_name='관련 팔로우업'),
            preserve_default=False,
        ),
    ]
