# Generated by Django 5.2.3 on 2025-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_history_action_type_alter_history_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('created_followup', '고객 정보 생성'), ('updated_followup', '고객 정보 수정'), ('created_schedule', '일정 생성'), ('updated_schedule', '일정 수정')], max_length=50, verbose_name='활동 유형'),
        ),
    ]
