# Generated by Django 5.2.3 on 2025-06-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_alter_history_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='delivery_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='납품 일정인 경우 금액을 입력하세요 (0원 입력 가능)', max_digits=15, null=True, verbose_name='납품 금액 (원)'),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('customer_meeting', '고객 미팅'), ('delivery_schedule', '납품 일정')], max_length=50, verbose_name='활동 유형'),
        ),
        migrations.AlterField(
            model_name='history',
            name='followup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reporting.followup', verbose_name='관련 고객 정보'),
        ),
    ]
