# Generated by Django 5.2.3 on 2025-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_history_delivery_amount_alter_history_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='핸드폰 번호'),
        ),
    ]
