# Generated by Django 5.2.3 on 2025-06-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='메일 주소'),
        ),
        migrations.AddField(
            model_name='followup',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='책임자'),
        ),
    ]
