# Generated by Django 5.2.3 on 2025-06-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_followup_email_followup_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='tax_invoice_issued',
            field=models.BooleanField(default=False, verbose_name='세금계산서 발행 여부'),
        ),
    ]
