# Generated by Django 5.2.3 on 2025-06-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_history_tax_invoice_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='delivery_items',
            field=models.TextField(blank=True, help_text='납품 일정인 경우 품목을 입력하세요', null=True, verbose_name='납품 품목'),
        ),
    ]
