# Generated by Django 5.2.3 on 2025-06-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_history_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='meeting_date',
            field=models.DateField(blank=True, help_text='고객 미팅인 경우 실제 미팅 날짜를 입력하세요', null=True, verbose_name='미팅 날짜'),
        ),
    ]
