# Generated by Django 5.2.3 on 2025-07-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_alter_history_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='service_status',
            field=models.CharField(blank=True, choices=[('received', '접수'), ('in_progress', '진행중'), ('cancelled', '취소'), ('completed', '완료')], default='received', help_text='서비스 활동인 경우에만 해당', max_length=20, null=True, verbose_name='서비스 상태'),
        ),
    ]
