# Generated by Django 5.2.3 on 2025-07-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_history_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='업체/학교명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '업체/학교',
                'verbose_name_plural': '업체/학교 목록',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='followup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.company', verbose_name='업체/학교명'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='부서/연구실명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='reporting.company', verbose_name='업체/학교')),
            ],
            options={
                'verbose_name': '부서/연구실',
                'verbose_name_plural': '부서/연구실 목록',
                'ordering': ['company__name', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='followup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.department', verbose_name='부서/연구실명'),
        ),
    ]
