# Generated by Django 5.2.3 on 2025-07-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_history_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10, unique=True, verbose_name='회사 코드')),
                ('company_name', models.CharField(max_length=100, verbose_name='회사명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사 목록',
                'ordering': ['company_name'],
            },
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (관리자)'), ('manager', 'Manager (매니저)'), ('salesman', 'SalesMan (실무자)')], default='salesman', max_length=20, verbose_name='권한'),
        ),
    ]
