# Generated by Django 5.2.3 on 2025-07-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0017_company_alter_followup_company_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporting.company', verbose_name='업체/학교명'),
            preserve_default=False,
        ),
    ]
