# Generated by Django 5.2.3 on 2025-07-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0018_userprofile_company_userprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin (최고관리자)'), ('company_admin', 'Company Admin (회사관리자)'), ('manager', 'Manager (매니저)'), ('salesman', 'SalesMan (실무자)')], default='salesman', max_length=20, verbose_name='권한'),
        ),
    ]
