# Generated by Django 5.2.3 on 2025-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_company_created_by_department_created_by_and_more'),
    ]

    operations = [
        # activity_type 필드가 이미 데이터베이스에 존재하므로 fake 마이그레이션으로 처리
        migrations.RunSQL(
            "-- activity_type field already exists in database",
            reverse_sql="-- no reverse operation needed"
        ),
    ]
