# Generated by Django 5.2.3 on 2025-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_auto_20250722_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='activity_type',
            field=models.CharField(choices=[('meeting', '미팅'), ('visit', '방문'), ('call', '통화'), ('other', '기타')], default='meeting', max_length=50, verbose_name='활동 유형'),
        ),
    ]
