# Generated by Django 5.2.3 on 2025-07-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_schedule_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity_type',
            field=models.CharField(choices=[('customer_meeting', '고객 미팅'), ('delivery', '납품 일정'), ('service', '서비스')], default='customer_meeting', max_length=50, verbose_name='일정 유형'),
        ),
    ]
