# Generated by Django 5.2.3 on 2025-07-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_alter_schedule_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('customer_meeting', '고객 미팅'), ('delivery_schedule', '납품 일정'), ('service', '서비스'), ('memo', '메모')], max_length=50, verbose_name='활동 유형'),
        ),
    ]
