# Generated by Django 5.2.3 on 2025-07-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_alter_history_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reporting.followup', verbose_name='관련 고객 정보'),
        ),
    ]
