# Generated by Django 5.2.3 on 2025-07-26 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_alter_history_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='매니저가 작성한 메모인 경우 매니저 정보가 저장됩니다', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_histories', to=settings.AUTH_USER_MODEL, verbose_name='실제 작성자'),
        ),
    ]
