# Generated by Django 5.2.3 on 2025-07-31 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0025_add_history_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='history_files/%Y/%m/', verbose_name='첨부파일')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reporting.history', verbose_name='관련 히스토리')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '히스토리 첨부파일',
                'verbose_name_plural': '히스토리 첨부파일 목록',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
