# Generated by Django 5.2.3 on 2025-07-31 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0026_historyfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='schedule_files/%Y/%m/', verbose_name='첨부파일')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reporting.schedule', verbose_name='관련 일정')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '일정 첨부파일',
                'verbose_name_plural': '일정 첨부파일 목록',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
