# Generated by Django 5.2.3 on 2025-08-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0027_schedulefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_download_excel',
            field=models.BooleanField(default=False, verbose_name='엑셀 다운로드 권한'),
        ),
    ]
