# Generated by Django 5.2.3 on 2025-09-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0028_userprofile_can_download_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='품목명')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('unit', models.CharField(default='개', max_length=50, verbose_name='단위')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='단가')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='총액')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items_set', to='reporting.schedule', verbose_name='일정')),
            ],
            options={
                'verbose_name': '납품 품목',
                'verbose_name_plural': '납품 품목 목록',
                'ordering': ['created_at'],
            },
        ),
    ]
