# Generated by Django 5.2.3 on 2025-09-10 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0029_deliveryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items_set', to='reporting.history', verbose_name='히스토리'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items_set', to='reporting.schedule', verbose_name='일정'),
        ),
    ]
