# Generated by Django 5.2.3 on 2025-09-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0030_deliveryitem_history_alter_deliveryitem_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('one_month', '한달'), ('three_months', '세달'), ('long_term', '장기')], default='three_months', max_length=20, verbose_name='우선순위'),
        ),
    ]
