# Generated by Django 5.2.3 on 2025-09-15 22:01

from django.db import migrations


def convert_priority_values(apps, schema_editor):
    """기존 우선순위 값을 새로운 체계로 변환"""
    FollowUp = apps.get_model('reporting', 'FollowUp')
    
    # 우선순위 매핑
    priority_mapping = {
        'low': 'one_month',      # 낮음 -> 한달
        'medium': 'three_months', # 보통 -> 세달
        'high': 'long_term',     # 높음 -> 장기
    }
    
    # 기존 데이터 변환
    for followup in FollowUp.objects.all():
        if followup.priority in priority_mapping:
            followup.priority = priority_mapping[followup.priority]
            followup.save()
    
    print(f"우선순위 변환 완료: {FollowUp.objects.count()}개 항목 처리됨")


def reverse_priority_values(apps, schema_editor):
    """변환 롤백을 위한 역변환 함수"""
    FollowUp = apps.get_model('reporting', 'FollowUp')
    
    # 역방향 매핑
    reverse_mapping = {
        'one_month': 'low',       # 한달 -> 낮음
        'three_months': 'medium', # 세달 -> 보통
        'long_term': 'high',      # 장기 -> 높음
    }
    
    # 데이터 역변환
    for followup in FollowUp.objects.all():
        if followup.priority in reverse_mapping:
            followup.priority = reverse_mapping[followup.priority]
            followup.save()
    
    print(f"우선순위 롤백 완료: {FollowUp.objects.count()}개 항목 처리됨")


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_alter_followup_priority'),
    ]

    operations = [
        migrations.RunPython(convert_priority_values, reverse_priority_values),
    ]
