# Generated by Django 5.2.3 on 2025-09-15 22:05

from django.db import migrations


def reset_delivery_data(apps, schema_editor):
    """기존 납품 데이터 초기화 - 새로운 구조화된 시스템으로 전환 준비"""
    History = apps.get_model('reporting', 'History')
    Schedule = apps.get_model('reporting', 'Schedule')
    DeliveryItem = apps.get_model('reporting', 'DeliveryItem')
    
    # 기존 History의 납품 관련 필드 초기화 (납품일은 관련 일정의 visit_date로 설정)
    delivery_histories = History.objects.filter(action_type='delivery_schedule')
    history_count = delivery_histories.count()
    
    if history_count > 0:
        for history in delivery_histories:
            # 관련 일정이 있으면 그 일정의 visit_date를 delivery_date로 설정
            if history.schedule and history.schedule.visit_date:
                history.delivery_date = history.schedule.visit_date
            else:
                history.delivery_date = None
            
            # 다른 납품 관련 필드들은 초기화
            history.delivery_amount = None
            history.delivery_items = None
            history.tax_invoice_issued = False
            history.save()
        
        print(f"History 납품 데이터 초기화 완료: {history_count}개 항목")
    
    # 기존 DeliveryItem 테이블 데이터 초기화
    delivery_item_count = DeliveryItem.objects.count()
    if delivery_item_count > 0:
        DeliveryItem.objects.all().delete()
        print(f"DeliveryItem 데이터 초기화 완료: {delivery_item_count}개 항목 삭제")
    
    # Schedule의 납품 관련 데이터도 확인
    delivery_schedules = Schedule.objects.filter(activity_type='delivery')
    schedule_count = delivery_schedules.count()
    
    if schedule_count > 0:
        print(f"Schedule 납품 일정 확인: {schedule_count}개 항목")
    
    print("=== 납품 데이터 초기화 완료 ===")
    print("납품일은 해당 일정의 방문일로 설정되었습니다.")
    print("새로운 구조화된 납품 시스템을 사용해주세요.")


def restore_delivery_data(apps, schema_editor):
    """롤백용 함수 - 실제로는 복구할 데이터가 없으므로 알림만 출력"""
    print("납품 데이터 롤백: 초기화된 데이터는 복구할 수 없습니다.")
    print("필요시 백업 데이터를 사용하여 수동으로 복구하세요.")


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0032_auto_20250916_0701'),
    ]

    operations = [
        migrations.RunPython(reset_delivery_data, restore_delivery_data),
    ]
