# Generated by Django 5.2.3 on 2025-09-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0033_auto_20250916_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='parent_history',
            field=models.ForeignKey(blank=True, help_text='매니저 메모의 경우 원본 히스토리를 참조합니다', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_memos', to='reporting.history', verbose_name='부모 히스토리'),
        ),
    ]
