# Generated by Django 5.2.3 on 2025-09-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0035_alter_history_parent_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='tax_invoice_issued',
            field=models.BooleanField(default=False, verbose_name='세금계산서 발행여부'),
        ),
    ]
