# Generated by Django 5.2.3 on 2025-09-16 21:58

from django.db import migrations


def update_three_months_to_long_term(apps, schema_editor):
    """기존 '세달' 우선순위 고객들을 '장기'로 변경"""
    FollowUp = apps.get_model('reporting', 'FollowUp')
    
    # '세달' 우선순위인 고객들을 '장기'로 변경
    updated_count = FollowUp.objects.filter(priority='three_months').update(priority='long_term')
    print(f"우선순위 변경 완료: {updated_count}건의 고객이 '세달'에서 '장기'로 변경되었습니다.")


def reverse_update_long_term_to_three_months(apps, schema_editor):
    """롤백 시 다시 '장기'를 '세달'로 변경 (선택적으로 사용)"""
    # 롤백은 복잡하므로 빈 함수로 두거나 필요시 구현
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_deliveryitem_tax_invoice_issued'),
    ]

    operations = [
        migrations.RunPython(
            update_three_months_to_long_term,
            reverse_update_long_term_to_three_months
        ),
    ]
