# Generated by Django 5.2.3 on 2025-09-18 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0037_auto_20250917_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='회사명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사용자 소속 회사',
                'verbose_name_plural': '사용자 소속 회사 목록',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('one_month', '한달'), ('three_months', '세달'), ('long_term', '장기')], default='long_term', max_length=20, verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='followup',
            name='user_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.usercompany', verbose_name='담당자 소속 회사'),
        ),
        migrations.AddField(
            model_name='history',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.usercompany', verbose_name='소속 회사'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.usercompany', verbose_name='소속 회사'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.usercompany', verbose_name='소속 회사'),
        ),
    ]
