# Generated by Django 5.2.3 on 2025-10-27 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0038_usercompany_alter_followup_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lead', '리드'), ('contact', '컨택'), ('quote', '견적'), ('negotiation', '협상'), ('closing', '클로징'), ('won', '수주'), ('lost', '실주')], max_length=20, unique=True, verbose_name='단계 코드')),
                ('display_name', models.CharField(max_length=50, verbose_name='표시명')),
                ('stage_order', models.IntegerField(unique=True, verbose_name='순서')),
                ('default_probability', models.IntegerField(default=50, verbose_name='기본 확률(%)')),
                ('avg_duration_days', models.IntegerField(default=7, verbose_name='평균 체류일')),
                ('color', models.CharField(default='#667eea', max_length=20, verbose_name='색상')),
                ('icon', models.CharField(default='fa-circle', max_length=50, verbose_name='아이콘')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('success_criteria', models.TextField(blank=True, verbose_name='다음 단계 조건')),
            ],
            options={
                'verbose_name': '펀넬 단계',
                'verbose_name_plural': '펀넬 단계 목록',
                'ordering': ['stage_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='제품 코드')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('category', models.CharField(choices=[('equipment', '장비'), ('software', '소프트웨어'), ('service', '서비스'), ('maintenance', '유지보수'), ('consumable', '소모품'), ('other', '기타')], max_length=50, verbose_name='카테고리')),
                ('standard_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='정상가')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='원가')),
                ('is_promo', models.BooleanField(default=False, verbose_name='프로모션 여부')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='프로모션 가격')),
                ('promo_start', models.DateField(blank=True, null=True, verbose_name='프로모션 시작일')),
                ('promo_end', models.DateField(blank=True, null=True, verbose_name='프로모션 종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='판매 가능')),
                ('description', models.TextField(blank=True, null=True, verbose_name='제품 설명')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='제품 사양')),
                ('total_quoted', models.IntegerField(default=0, verbose_name='총 견적 횟수')),
                ('total_sold', models.IntegerField(default=0, verbose_name='총 판매 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품 목록',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('lead', '리드'), ('contact', '컨택'), ('quote', '견적'), ('negotiation', '협상'), ('closing', '클로징'), ('won', '수주'), ('lost', '실주')], default='lead', max_length=20, verbose_name='현재 단계')),
                ('stage_entry_date', models.DateField(auto_now_add=True, verbose_name='단계 진입일')),
                ('expected_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='예상 매출')),
                ('weighted_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='가중 매출')),
                ('probability', models.IntegerField(default=50, verbose_name='성공 확률(%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='예상 계약일')),
                ('stage_history', models.JSONField(default=list, verbose_name='단계 이력')),
                ('total_quotes_sent', models.IntegerField(default=0, verbose_name='발송 견적 수')),
                ('total_meetings', models.IntegerField(default=0, verbose_name='총 미팅 수')),
                ('avg_response_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='평균 응답 시간(시간)')),
                ('won_date', models.DateField(blank=True, null=True, verbose_name='수주일')),
                ('lost_date', models.DateField(blank=True, null=True, verbose_name='실주일')),
                ('lost_reason', models.TextField(blank=True, null=True, verbose_name='실주 사유')),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='실제 매출')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('followup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity', to='reporting.followup', verbose_name='관련 고객')),
            ],
            options={
                'verbose_name': '영업 기회',
                'verbose_name_plural': '영업 기회 목록',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='견적번호')),
                ('quote_date', models.DateField(auto_now_add=True, verbose_name='견적일')),
                ('valid_until', models.DateField(verbose_name='유효기한')),
                ('stage', models.CharField(choices=[('draft', '초안'), ('sent', '발송완료'), ('review', '검토중'), ('negotiation', '협상중'), ('approved', '승인'), ('rejected', '거절'), ('expired', '만료'), ('converted', '계약전환')], default='draft', max_length=20, verbose_name='견적 상태')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='소계')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='할인율(%)')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='할인액')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총액')),
                ('probability', models.IntegerField(default=50, verbose_name='성공 확률(%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='예상 계약일')),
                ('weighted_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='가중 매출')),
                ('converted_to_delivery', models.BooleanField(default=False, verbose_name='납품 전환 여부')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('customer_feedback', models.TextField(blank=True, null=True, verbose_name='고객 피드백')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('converted_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='reporting.history', verbose_name='전환된 납품 기록')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='reporting.followup', verbose_name='관련 고객')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='reporting.schedule', verbose_name='관련 일정')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '견적',
                'verbose_name_plural': '견적 목록',
                'ordering': ['-quote_date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='단가')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='할인율(%)')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='소계')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상세 설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.product', verbose_name='제품')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reporting.quote', verbose_name='견적')),
            ],
            options={
                'verbose_name': '견적 항목',
                'verbose_name_plural': '견적 항목 목록',
                'ordering': ['order', 'id'],
            },
        ),
    ]
