# Generated by Django 5.2.3 on 2025-10-27 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0039_funnelstage_product_opportunitytracking_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='계약이 예상되는 날짜', null=True, verbose_name='예상 계약일'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='예상되는 거래 금액', max_digits=15, null=True, verbose_name='예상 매출액'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='reporting.opportunitytracking', verbose_name='영업 기회'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='probability',
            field=models.IntegerField(blank=True, help_text='0-100 사이의 값', null=True, verbose_name='성공 확률 (%)'),
        ),
    ]
