# Generated by Django 5.2.3 on 2025-10-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0040_schedule_expected_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity_type',
            field=models.CharField(choices=[('customer_meeting', '고객 미팅'), ('quote', '견적 제출'), ('delivery', '납품 일정'), ('service', '서비스')], default='customer_meeting', max_length=50, verbose_name='일정 유형'),
        ),
    ]
