# Generated by Django 5.2.3 on 2025-10-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0041_alter_schedule_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='purchase_confirmed',
            field=models.BooleanField(default=False, help_text='구매가 확정된 경우 체크 (클로징 단계로 전환)', verbose_name='구매 확정'),
        ),
    ]
