# Generated by Django 5.2.3 on 2025-10-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_schedule_purchase_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitytracking',
            name='backlog_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='예정된 일정의 총 매출액', max_digits=15, verbose_name='수주 금액'),
        ),
        migrations.AddField(
            model_name='opportunitytracking',
            name='revenue_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='완료된 일정의 총 매출액', max_digits=15, verbose_name='실주 금액'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='revenue_type',
            field=models.CharField(blank=True, choices=[('backlog', '수주'), ('revenue', '실주')], help_text='예정=수주, 완료=실주', max_length=20, null=True, verbose_name='매출 유형'),
        ),
    ]
