# Generated by Django 5.2.3 on 2025-10-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0043_opportunitytracking_backlog_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitytracking',
            name='revenue_amount',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='revenue_type',
        ),
    ]
