# Generated by Django 5.2.3 on 2025-10-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0044_remove_opportunitytracking_revenue_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitytracking',
            name='title',
            field=models.CharField(blank=True, help_text="예: '장비 A 구매', '소모품 정기 공급' 등", max_length=200, null=True, verbose_name='영업 기회 제목'),
        ),
        migrations.AlterField(
            model_name='opportunitytracking',
            name='followup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='reporting.followup', verbose_name='관련 고객'),
        ),
    ]
