# Generated by Django 5.2.3 on 2025-10-28 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0045_opportunitytracking_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitytracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 28, 22, 17, 53, 809819, tzinfo=datetime.timezone.utc), verbose_name='생성일'),
            preserve_default=False,
        ),
    ]
