# Generated by Django 5.2.3 on 2025-10-30 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0046_opportunitytracking_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='선결제 금액')),
                ('balance', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='잔액')),
                ('payment_date', models.DateField(verbose_name='입금 날짜')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('transfer', '계좌이체'), ('card', '카드')], default='transfer', max_length=20, verbose_name='입금 방법')),
                ('payer_name', models.CharField(blank=True, max_length=100, verbose_name='입금자명')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('status', models.CharField(choices=[('active', '활성'), ('depleted', '소진'), ('cancelled', '취소')], default='active', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='취소 사유')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.company', verbose_name='업체/학교')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayments', to='reporting.followup', verbose_name='고객')),
            ],
            options={
                'verbose_name': '선결제',
                'verbose_name_plural': '선결제 목록',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrepaymentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='품목명')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='차감 금액')),
                ('remaining_balance', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='사용 후 잔액')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='사용 일시')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('prepayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='reporting.prepayment', verbose_name='선결제')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_usages', to='reporting.schedule', verbose_name='납품 일정')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.deliveryitem', verbose_name='납품 품목')),
            ],
            options={
                'verbose_name': '선결제 사용 내역',
                'verbose_name_plural': '선결제 사용 내역 목록',
                'ordering': ['-used_at'],
            },
        ),
    ]
