# Generated by Django 5.2.3 on 2025-10-30 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0047_prepayment_prepaymentusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='prepayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_schedules', to='reporting.prepayment', verbose_name='사용한 선결제'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='prepayment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='선결제에서 차감된 금액', max_digits=15, null=True, verbose_name='선결제 사용 금액'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='use_prepayment',
            field=models.BooleanField(default=False, help_text='선결제 잔액에서 차감하는 경우 체크', verbose_name='선결제 사용'),
        ),
    ]
