# Generated by Django 5.2.3 on 2025-11-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0048_schedule_prepayment_schedule_prepayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='reporting.product', verbose_name='제품'),
        ),
    ]
