# Generated by Django 5.2.3 on 2025-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0049_deliveryitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('equipment', '장비'), ('software', '소프트웨어'), ('service', '서비스'), ('maintenance', '유지보수'), ('consumable', '소모품'), ('other', '기타')], max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='제품 코드 (품번)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='정상가 (단가)'),
        ),
    ]
