# Generated by Django 5.2.3 on 2025-11-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0050_alter_product_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_code'], 'verbose_name': '제품', 'verbose_name_plural': '제품 목록'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
    ]
