# Generated by Django 5.2.3 on 2025-11-08 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0051_alter_product_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
