# Generated by Django 5.2.3 on 2025-11-08 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0052_remove_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quoteitems', to='reporting.product', verbose_name='제품'),
        ),
    ]
