# Generated by Django 5.2.3 on 2025-11-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0053_alter_quoteitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnelstage',
            name='name',
            field=models.CharField(choices=[('lead', '리드'), ('contact', '컨택'), ('quote', '견적'), ('closing', '클로징'), ('won', '수주'), ('quote_lost', '견적실패')], max_length=20, unique=True, verbose_name='단계 코드'),
        ),
        migrations.AlterField(
            model_name='opportunitytracking',
            name='current_stage',
            field=models.CharField(choices=[('lead', '리드'), ('contact', '컨택'), ('quote', '견적'), ('closing', '클로징'), ('won', '수주'), ('quote_lost', '견적실패')], default='lead', max_length=20, verbose_name='현재 단계'),
        ),
    ]
