# Generated by Django 5.2.3 on 2025-11-17 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0055_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정 제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='일정 내용')),
                ('schedule_date', models.DateField(verbose_name='일정 날짜')),
                ('schedule_time', models.TimeField(verbose_name='일정 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '개인 일정',
                'verbose_name_plural': '개인 일정 목록',
                'ordering': ['-schedule_date', '-schedule_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_created_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryitem',
            name='deliveryitem_schedule_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryitem',
            name='deliveryitem_history_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryitem',
            name='deliveryitem_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='department_company_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='followup_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='followup_user_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='followup_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='followup_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='history',
            name='history_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='history',
            name='history_type_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='history',
            name='history_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunitytracking',
            name='opportunity_followup_stage_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunitytracking',
            name='opportunity_stage_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_type_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercompany',
            name='usercompany_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='userprofile_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='userprofile_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='userprofile_company_role_idx',
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('customer_meeting', '고객 미팅'), ('quote', '견적'), ('delivery_schedule', '납품 일정'), ('service', '서비스'), ('memo', '메모')], max_length=50, verbose_name='활동 유형'),
        ),
        migrations.AddField(
            model_name='personalschedule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.usercompany', verbose_name='소속 회사'),
        ),
        migrations.AddField(
            model_name='personalschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_schedules', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='history',
            name='personal_schedule',
            field=models.ForeignKey(blank=True, help_text='개인 일정에 대한 댓글', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reporting.personalschedule', verbose_name='관련 개인 일정'),
        ),
    ]
