# Generated by Django 5.2.3 on 2025-11-20 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0057_product_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', '견적서'), ('transaction_statement', '거래명세서'), ('invoice', '세금계산서'), ('delivery_note', '납품서'), ('contract', '계약서'), ('other', '기타')], max_length=50, verbose_name='서류 종류')),
                ('name', models.CharField(max_length=200, verbose_name='서류명')),
                ('file', models.FileField(upload_to='document_templates/%Y/%m/', verbose_name='파일')),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10, verbose_name='파일 형식')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 템플릿 여부')),
                ('email_subject_template', models.CharField(blank=True, help_text='예: {customer_name}님께 {document_type} 발송', max_length=200, verbose_name='이메일 제목 템플릿')),
                ('email_body_template', models.TextField(blank=True, help_text='향후 이메일 발송 시 사용될 본문 템플릿', verbose_name='이메일 본문 템플릿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='reporting.usercompany', verbose_name='소속 회사')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '서류 템플릿',
                'verbose_name_plural': '서류 템플릿 목록',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('company', 'document_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='수신자 이메일')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='수신자명')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='email_attachments/%Y/%m/', verbose_name='첨부 파일')),
                ('status', models.CharField(choices=[('pending', '발송 대기'), ('sent', '발송 완료'), ('failed', '발송 실패')], default='pending', max_length=20, verbose_name='발송 상태')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 일시')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.documenttemplate', verbose_name='첨부 서류 템플릿')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.followup', verbose_name='관련 팔로우업')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.schedule', verbose_name='관련 일정')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
            ],
            options={
                'verbose_name': '이메일 발송 로그',
                'verbose_name_plural': '이메일 발송 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
