# Generated by Django 5.2.3 on 2025-11-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0058_documenttemplate_emaillog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together=set(),
        ),
    ]
