# Generated by Django 5.2.3 on 2025-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0059_alter_documenttemplate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=200, verbose_name='규격'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='EA', max_length=50, verbose_name='단위'),
        ),
    ]
