# Generated by Django 5.2.3 on 2025-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0060_product_specification_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='unit',
            field=models.CharField(default='EA', max_length=50, verbose_name='단위'),
        ),
    ]
