# Generated by Django 5.2.3 on 2025-11-21 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0061_change_deliveryitem_unit_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', '견적서'), ('transaction_statement', '거래명세서'), ('invoice', '세금계산서'), ('delivery_note', '납품서'), ('contract', '계약서'), ('other', '기타')], max_length=50, verbose_name='서류 종류')),
                ('transaction_number', models.CharField(max_length=50, verbose_name='거래번호')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel')], max_length=10, verbose_name='출력 형식')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_logs', to='reporting.usercompany', verbose_name='소속 회사')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.schedule', verbose_name='관련 일정')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '서류 생성 로그',
                'verbose_name_plural': '서류 생성 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='reporting_d_company_b5891f_idx'), models.Index(fields=['document_type', 'created_at'], name='reporting_d_documen_e7530b_idx')],
            },
        ),
    ]
