# Generated by Django 5.2.3 on 2025-11-21 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0062_documentgenerationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at', '-received_at', '-created_at'], 'verbose_name': '이메일', 'verbose_name_plural': '이메일 목록'},
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bcc_emails',
            field=models.TextField(blank=True, help_text='쉼표로 구분', verbose_name='숨은 참조 (BCC)'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='HTML 본문'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='cc_emails',
            field=models.TextField(blank=True, help_text='쉼표로 구분', verbose_name='참조 (CC)'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('sent', '발신'), ('received', '수신')], default='sent', max_length=20, verbose_name='메일 타입'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Gmail 메시지 ID'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='gmail_thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Gmail 스레드 ID'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='reporting.emaillog', verbose_name='답장 대상 메일'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='읽음 여부'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='received_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='수신 일시'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='발신자 이메일 주소'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gmail 연결 일시'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='연결된 Gmail 주소'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_token',
            field=models.JSONField(blank=True, help_text='암호화된 토큰 저장', null=True, verbose_name='Gmail OAuth 토큰'),
        ),
        migrations.AlterField(
            model_name='documentgenerationlog',
            name='document_type',
            field=models.CharField(choices=[('quotation', '견적서'), ('transaction_statement', '거래명세서'), ('delivery_note', '납품서')], max_length=50, verbose_name='서류 종류'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('quotation', '견적서'), ('transaction_statement', '거래명세서'), ('delivery_note', '납품서')], max_length=50, verbose_name='서류 종류'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='reporting.followup', verbose_name='관련 팔로우업'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='reporting.schedule', verbose_name='관련 일정'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='발신자 (CRM 사용자)'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='발송 일시'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', '발송 대기'), ('sent', '발송 완료'), ('received', '수신'), ('failed', '발송 실패')], default='pending', max_length=20, verbose_name='발송 상태'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='제목'),
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 기본 명함, 영문 명함', max_length=100, verbose_name='명함 이름')),
                ('full_name', models.CharField(max_length=100, verbose_name='이름')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='직책')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='부서')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='전화번호')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='휴대폰')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='주소')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='팩스')),
                ('logo_url', models.URLField(blank=True, verbose_name='로고 URL')),
                ('signature_html', models.TextField(blank=True, help_text='커스텀 HTML 서명', verbose_name='HTML 서명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 명함')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_cards', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '명함',
                'verbose_name_plural': '명함 목록',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='business_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.businesscard', verbose_name='사용된 명함'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['-sent_at', '-received_at'], name='reporting_e_sent_at_8e640a_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['gmail_thread_id'], name='reporting_e_gmail_t_b8190d_idx'),
        ),
    ]
