# Generated by Django 5.2.3 on 2025-11-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0063_gmail_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화 일시'),
        ),
    ]
