# Generated by Django 5.2.3 on 2025-11-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0064_userprofile_gmail_last_sync_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='attachments_info',
            field=models.JSONField(blank=True, default=list, verbose_name='첨부파일 목록'),
        ),
    ]
