# Generated by Django 5.2.3 on 2025-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0065_emaillog_attachments_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_card_logos/', verbose_name='로고 이미지'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='logo_link_url',
            field=models.URLField(blank=True, help_text='로고를 클릭했을 때 이동할 URL', verbose_name='로고 링크 URL'),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='logo_url',
            field=models.URLField(blank=True, help_text='로고를 클릭했을 때 이동할 URL', verbose_name='로고 이미지 URL'),
        ),
    ]
