# Generated by Django 5.2.3 on 2025-11-23 23:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0066_businesscard_logo_businesscard_logo_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
