# Generated by Django 5.2.3 on 2025-11-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0067_alter_businesscard_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='ai_score',
            field=models.IntegerField(default=50, help_text='0-100점, 거래 실적/수주율/응답성 등 종합 평가', verbose_name='AI 점수'),
        ),
        migrations.AddField(
            model_name='followup',
            name='customer_grade',
            field=models.CharField(choices=[('VIP', 'VIP (최우수 고객)'), ('A', 'A (우수 고객)'), ('B', 'B (일반 고객)'), ('C', 'C (잠재 고객)'), ('D', 'D (저관심 고객)')], default='C', help_text='AI가 자동 산정하는 고객 등급 (VIP/A/B/C/D)', max_length=10, verbose_name='고객 등급'),
        ),
        migrations.AddField(
            model_name='followup',
            name='grade_metrics',
            field=models.JSONField(default=dict, help_text='등급이 어떻게 계산되었는지 저장 (투명성)', verbose_name='등급 산정 기준'),
        ),
        migrations.AddField(
            model_name='followup',
            name='last_grade_updated',
            field=models.DateTimeField(blank=True, help_text='마지막으로 AI 등급이 계산된 시점', null=True, verbose_name='등급 갱신일'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('one_month', '한달'), ('three_months', '세달'), ('long_term', '장기')], default='long_term', max_length=20, verbose_name='우선순위 (구형)'),
        ),
    ]
