# Generated by Django 5.2.3 on 2025-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0068_followup_ai_score_followup_customer_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('urgent', '긴급'), ('followup', '팔로업'), ('scheduled', '예정')], default='scheduled', max_length=20, verbose_name='우선순위'),
        ),
    ]
