# Generated by Django 5.2.3 on 2025-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0069_alter_followup_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_ai',
            field=models.BooleanField(default=False, help_text='AI 이메일 생성, 고객 분석, 자동 요약 등 GPT 기능 사용 가능 여부', verbose_name='AI 기능 사용 권한'),
        ),
    ]
