# Generated by Django 5.2.3 on 2025-11-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0070_add_ai_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='ai_grade_reasoning',
            field=models.TextField(blank=True, help_text='GPT가 생성한 등급 평가 근거', null=True, verbose_name='AI 등급 평가 근거'),
        ),
        migrations.AddField(
            model_name='followup',
            name='ai_grade_score',
            field=models.IntegerField(blank=True, help_text='GPT 기반 등급 점수 (0-100)', null=True, verbose_name='AI 등급 점수'),
        ),
        migrations.AddField(
            model_name='followup',
            name='ai_grade_updated_at',
            field=models.DateTimeField(blank=True, help_text='GPT 기반 등급이 마지막으로 업데이트된 시점', null=True, verbose_name='AI 등급 갱신일'),
        ),
    ]
