# Generated by Django 5.2.3 on 2025-11-27 21:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0071_followup_ai_grade_reasoning_followup_ai_grade_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='파일'),
        ),
    ]
