# Generated by Django 5.2.3 on 2025-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0072_alter_documenttemplate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_card_logos/%Y/', verbose_name='로고'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(upload_to='document_templates/%Y/', verbose_name='파일'),
        ),
    ]
