# Generated by Django 5.2.3 on 2025-12-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0073_cloudinary_to_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('one_month', '한달'), ('three_months', '세달'), ('long_term', '장기')], default='long_term', max_length=20, verbose_name='우선순위'),
        ),
    ]
