# Generated by Django 5.2.3 on 2025-12-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0074_change_priority_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('urgent', '긴급'), ('followup', '팔로업'), ('scheduled', '예정'), ('long_term', '장기')], default='scheduled', max_length=20, verbose_name='우선순위'),
        ),
    ]
