# Generated by Django 5.2.3 on 2025-12-02 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0075_add_long_term_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='라벨명')),
                ('color', models.CharField(default='#667eea', help_text='HEX 색상 코드 (예: #667eea)', max_length=7, verbose_name='색상')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('user_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_labels', to='reporting.usercompany', verbose_name='소속 회사')),
            ],
            options={
                'verbose_name': '영업 기회 라벨',
                'verbose_name_plural': '영업 기회 라벨 목록',
                'ordering': ['name'],
                'unique_together': {('name', 'user_company')},
            },
        ),
        migrations.AddField(
            model_name='opportunitytracking',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='reporting.opportunitylabel', verbose_name='라벨'),
        ),
    ]
