# Generated by Django 5.2.3 on 2025-12-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0076_add_opportunity_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reporting.schedule', verbose_name='관련 일정'),
        ),
    ]
