# Generated by Django 5.2.3 on 2025-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0077_history_schedule_cascade_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='보관됨'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False, verbose_name='중요 표시'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='휴지통'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시'),
        ),
        migrations.AlterField(
            model_name='funnelstage',
            name='name',
            field=models.CharField(choices=[('lead', '리드'), ('contact', '컨택'), ('quote', '견적'), ('closing', '클로징'), ('won', '수주'), ('quote_lost', '견적실패'), ('excluded', '펀넬제외')], max_length=20, unique=True, verbose_name='단계 코드'),
        ),
        migrations.AlterField(
            model_name='opportunitytracking',
            name='current_stage',
            field=models.CharField(choices=[('lead', '리드'), ('contact', '컨택'), ('quote', '견적'), ('closing', '클로징'), ('won', '수주'), ('quote_lost', '견적실패'), ('excluded', '펀넬제외')], default='lead', max_length=20, verbose_name='현재 단계'),
        ),
    ]
