# Generated by Django 5.2.3 on 2025-12-06 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0078_add_email_status_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='발신자 이메일'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='from_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='발신자명'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='True=발신, False=수신', verbose_name='발신 여부'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Gmail Message-ID 또는 IMAP Message-ID', max_length=500, verbose_name='메시지 ID'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail API'), ('imap', 'IMAP'), ('smtp', 'SMTP')], default='gmail', max_length=20, verbose_name='이메일 제공자'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, help_text='이메일 스레드 추적용', max_length=500, verbose_name='스레드 ID'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='수신자 이메일'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='to_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='수신자명'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_provider',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office365'), ('imap', 'Custom IMAP/SMTP')], default='gmail', max_length=20, verbose_name='이메일 제공업체'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='IMAP 연결 일시'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='IMAP 이메일 주소'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_host',
            field=models.CharField(blank=True, help_text='예: imap.gmail.com', max_length=255, verbose_name='IMAP 서버'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='IMAP 마지막 동기화 일시'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_password',
            field=models.CharField(blank=True, help_text='암호화 저장', max_length=255, verbose_name='IMAP 비밀번호'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_port',
            field=models.IntegerField(default=993, verbose_name='IMAP 포트'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, verbose_name='IMAP SSL 사용'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP 사용자명'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='예: smtp.gmail.com', max_length=255, verbose_name='SMTP 서버'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='암호화 저장', max_length=255, verbose_name='SMTP 비밀번호'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP 포트'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP TLS 사용'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP 사용자명'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='수신자 이메일 (deprecated)'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='수신자명 (deprecated)'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='발신자 (CRM 사용자)'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='발신자 이메일 주소 (deprecated)'),
        ),
    ]
