# Generated by Django 5.2.3 on 2025-12-16 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0079_emaillog_from_email_emaillog_from_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('color', models.CharField(default='#007bff', help_text='HEX 색상 코드 (예: #007bff)', max_length=7, verbose_name='색상 코드')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '고객 카테고리',
                'verbose_name_plural': '고객 카테고리 목록',
                'ordering': ['order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='followup',
            name='category',
            field=models.ForeignKey(blank=True, help_text='고객 분류 카테고리', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.customercategory', verbose_name='카테고리'),
        ),
    ]
