# Generated by Django 5.2.3 on 2025-12-16 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0080_customercategory_followup_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customercategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reporting.customercategory', verbose_name='상위 카테고리'),
        ),
        migrations.AlterUniqueTogether(
            name='customercategory',
            unique_together={('user', 'name', 'parent')},
        ),
    ]
