# Generated by Django 5.2.3 on 2025-12-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0081_alter_customercategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='category',
        ),
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.ForeignKey(blank=True, help_text='부서 분류 카테고리', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.customercategory', verbose_name='카테고리'),
        ),
    ]
