# Generated by Django 5.2.3 on 2026-02-16 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0082_remove_followup_category_department_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='대상 연도')),
                ('target_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='목표 매출액')),
                ('is_auto_added', models.BooleanField(default=True, help_text='매출 기반 자동 추가(True) / 사용자 수동 추가(False)', verbose_name='자동 추가 여부')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_targets', to='reporting.department', verbose_name='부서/연구실')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_targets', to=settings.AUTH_USER_MODEL, verbose_name='담당 영업사원')),
            ],
            options={
                'verbose_name': '펀넬 목표',
                'verbose_name_plural': '펀넬 목표 목록',
                'ordering': ['-year', 'department__company__name', 'department__name'],
                'indexes': [models.Index(fields=['user', 'year'], name='reporting_f_user_id_62c0c9_idx'), models.Index(fields=['department', 'year'], name='reporting_f_departm_32c6a6_idx')],
                'unique_together': {('user', 'department', 'year')},
            },
        ),
    ]
