# Generated by Django 5.2.3 on 2026-02-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0083_funneltarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='meeting_confirmed_facts',
            field=models.TextField(blank=True, help_text='미팅에서 직접 확인한 사실을 기록하세요', null=True, verbose_name='내가 확인한 사실'),
        ),
        migrations.AddField(
            model_name='history',
            name='meeting_next_action',
            field=models.TextField(blank=True, help_text='미팅 이후 수행할 다음 액션을 기록하세요', null=True, verbose_name='다음 액션'),
        ),
        migrations.AddField(
            model_name='history',
            name='meeting_obstacles',
            field=models.TextField(blank=True, help_text='영업 진행에 장애물이나 반대 의견을 기록하세요', null=True, verbose_name='장애물/반대'),
        ),
        migrations.AddField(
            model_name='history',
            name='meeting_researcher_quote',
            field=models.TextField(blank=True, help_text='연구원이 직접 한 말을 인용하여 기록하세요', null=True, verbose_name='연구원이 한 말(직접 인용)'),
        ),
        migrations.AddField(
            model_name='history',
            name='meeting_situation',
            field=models.TextField(blank=True, help_text='미팅에서 파악한 오늘의 상황을 기록하세요', null=True, verbose_name='오늘 상황'),
        ),
    ]
