# Generated by Django 5.2.3 on 2026-04-21 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0085_migrate_meeting_content_to_situation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메모 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='reporting.department', verbose_name='부서/연구실')),
            ],
            options={
                'verbose_name': '부서 메모',
                'verbose_name_plural': '부서 메모 목록',
                'db_table': 'department_memo',
                'ordering': ['-updated_at'],
            },
        ),
    ]
