# Generated by Django 5.2.3 on 2026-04-21 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0086_add_department_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='주 시작일 (월요일)')),
                ('week_end', models.DateField(verbose_name='주 종료일 (금요일)')),
                ('title', models.CharField(max_length=200, verbose_name='보고서 제목')),
                ('activity_notes', models.TextField(blank=True, verbose_name='영업 활동 내용')),
                ('quote_delivery_notes', models.TextField(blank=True, verbose_name='견적/납품 내용')),
                ('other_notes', models.TextField(blank=True, verbose_name='기타 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '주간보고',
                'verbose_name_plural': '주간보고 목록',
                'db_table': 'weekly_report',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
