# Generated by Django 5.2.3 on 2026-04-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0087_add_weekly_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='pipeline_stage',
            field=models.CharField(choices=[('potential', '잠재'), ('contact', '접촉/미팅'), ('quote', '견적 제출'), ('negotiation', '협상'), ('won', '수주'), ('lost', '실주')], default='potential', help_text='영업 파이프라인 단계 (칸반 보드용)', max_length=20, verbose_name='파이프라인 단계'),
        ),
    ]
