# Generated by Django 5.2.3 on 2026-04-25 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0088_add_followup_pipeline_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='next_action',
            field=models.TextField(blank=True, help_text='이번 활동 이후 수행할 다음 액션을 기록하세요', null=True, verbose_name='다음 할 일'),
        ),
        migrations.AddField(
            model_name='history',
            name='next_action_date',
            field=models.DateField(blank=True, help_text='다음 액션 예정일을 선택하세요', null=True, verbose_name='다음 예정일'),
        ),
        migrations.AddField(
            model_name='history',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='관리자 검토 완료 시각'),
        ),
        migrations.AddField(
            model_name='history',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_histories', to=settings.AUTH_USER_MODEL, verbose_name='검토 관리자'),
        ),
    ]
