# Generated by Django 5.2.3 on 2026-04-26 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0089_history_review_and_next_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='관리자 코멘트'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토 완료 시각'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='검토 관리자'),
        ),
    ]
