# Generated by Django 5.2.3 on 2026-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0090_add_weekly_report_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='pipeline_manually_set',
            field=models.BooleanField(default=False, help_text='True이면 자동 동기화에서 이 카드의 단계를 변경하지 않음', verbose_name='파이프라인 수동 설정'),
        ),
    ]
