# Generated by Django 5.2.3 on 2026-04-29 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0091_add_pipeline_manually_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_requested', '미요청'), ('requested', '발행요청'), ('issued', '발행완료'), ('cancelled', '발행취소'), ('on_hold', '보류')], db_index=True, default='requested', max_length=20, verbose_name='상태')),
                ('supply_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='공급가액')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='합계금액')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('request_memo', models.TextField(blank=True, verbose_name='요청 메모')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='발행 처리일시')),
                ('issue_memo', models.TextField(blank=True, verbose_name='발행 메모')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소/보류일시')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='취소/보류 사유')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='취소/보류 처리자')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoice_requests', to='reporting.followup', verbose_name='관련 거래처')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices_issued', to=settings.AUTH_USER_MODEL, verbose_name='발행 처리자')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoice_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoice_requests', to='reporting.schedule', verbose_name='관련 납품 일정')),
            ],
            options={
                'verbose_name': '세금계산서 요청',
                'verbose_name_plural': '세금계산서 요청 목록',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['followup', 'status'], name='reporting_t_followu_609852_idx'), models.Index(fields=['schedule', 'status'], name='reporting_t_schedul_e0ebe7_idx')],
            },
        ),
    ]
