# Generated by Django 5.2.3 on 2026-04-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0092_add_tax_invoice_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='vat_mode',
            field=models.CharField(choices=[('excluded', '부가세 별도'), ('included', '부가세 포함'), ('none', '부가세 없음 / 0원')], default='excluded', help_text='부가세 별도: 공급가+VAT10%, 부가세 포함: 입력금액에 VAT포함, 부가세 없음: VAT=0', max_length=20, verbose_name='부가세 모드'),
        ),
    ]
