# Generated by Django 5.2.3 on 2026-05-07 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0093_add_schedule_vat_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['user', '-created_at'], name='follow_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['user', 'pipeline_stage'], name='follow_user_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['user', 'department'], name='follow_user_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', '-created_at'], name='hist_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'action_type', '-created_at'], name='hist_user_action_date_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'parent_history', '-created_at'], name='hist_user_parent_date_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'next_action_date'], name='hist_user_next_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['schedule', '-created_at'], name='hist_sched_created_idx'),
        ),
        migrations.AddIndex(
            model_name='personalschedule',
            index=models.Index(fields=['user', 'schedule_date', 'schedule_time'], name='pers_user_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='prepayment',
            index=models.Index(fields=['created_by', 'payment_date'], name='prepay_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prepayment',
            index=models.Index(fields=['created_by', 'status'], name='prepay_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'visit_date'], name='sched_user_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'activity_type', 'status', 'visit_date'], name='sched_user_act_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['visit_date', 'activity_type', 'status'], name='sched_date_act_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['followup', 'activity_type'], name='sched_follow_act_idx'),
        ),
    ]
