# Generated by Django 5.2.3 on 2026-05-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0094_followup_follow_user_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='할인율(%)'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='discount_unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='할인단가'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='quote_extra_notes',
            field=models.TextField(blank=True, null=True, verbose_name='견적 기타사항'),
        ),
    ]
