# Generated by Django 5.2.3 on 2026-05-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0095_deliveryitem_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgenerationlog',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='generated_documents/%Y/%m/', verbose_name='생성 파일'),
        ),
        migrations.AddField(
            model_name='documentgenerationlog',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='파일 크기 (bytes)'),
        ),
        migrations.AddField(
            model_name='documentgenerationlog',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='파일명'),
        ),
    ]
