# Generated by Django 5.2.3 on 2026-05-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0096_documentgenerationlog_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='quote_group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='견적서 구분'),
        ),
        migrations.AddField(
            model_name='documentgenerationlog',
            name='quote_group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='견적서 구분'),
        ),
    ]
