# Generated by Django 5.2.3 on 2026-05-13 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0098_schedule_quote_group_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='source_quote_item',
            field=models.ForeignKey(blank=True, help_text='견적 품목을 납품으로 불러온 경우 원본 견적 품목 라인입니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_imports', to='reporting.deliveryitem', verbose_name='원본 견적 품목'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='source_quote_schedule',
            field=models.ForeignKey(blank=True, help_text='견적 품목을 납품으로 불러온 경우 원본 견적 일정입니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_delivery_items', to='reporting.schedule', verbose_name='원본 견적 일정'),
        ),
    ]
