# Generated by Django 5.2.3 on 2026-05-13 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0099_delivery_item_source_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkspaceActionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=160, verbose_name='AI 액션 ID')),
                ('action_kind', models.CharField(blank=True, default='', max_length=50, verbose_name='AI 액션 유형')),
                ('status', models.CharField(choices=[('answered', '답변 기록'), ('next_action', '다음 액션'), ('resolved', '종료'), ('dismissed', '목록 제외')], default='answered', max_length=20, verbose_name='처리 상태')),
                ('feedback', models.TextField(verbose_name='현장 답변')),
                ('ai_result', models.JSONField(blank=True, default=dict, verbose_name='AI 판단 결과')),
                ('action_snapshot', models.JSONField(blank=True, default=dict, verbose_name='액션 스냅샷')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_workspace_action_feedbacks', to='reporting.followup', verbose_name='관련 고객')),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_workspace_action_feedbacks', to='reporting.history', verbose_name='생성된 영업노트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workspace_action_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 추천 실행 답변',
                'verbose_name_plural': 'AI 추천 실행 답변 목록',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'action_id'], name='ai_fb_user_action_idx'), models.Index(fields=['user', 'status', '-updated_at'], name='ai_fb_user_status_idx'), models.Index(fields=['followup', 'status'], name='ai_fb_follow_status_idx')],
                'unique_together': {('user', 'action_id')},
            },
        ),
    ]
