# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0100_aiworkspaceactionfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkspaceQuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all', '전체 부서'), ('department', '부서')], default='department', max_length=20, verbose_name='질문 범위')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='답변 스냅샷')),
                ('source', models.CharField(blank=True, default='', max_length=30, verbose_name='답변 출처')),
                ('rating', models.CharField(choices=[('helpful', '좋음'), ('needs_style', '방향 수정'), ('incorrect', '틀림')], max_length=20, verbose_name='평가')),
                ('comment', models.TextField(blank=True, default='', verbose_name='수정 코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_workspace_question_feedbacks', to='reporting.department', verbose_name='관련 부서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workspace_question_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 질문 답변 피드백',
                'verbose_name_plural': 'AI 질문 답변 피드백 목록',
                'ordering': ['-updated_at'],
                'indexes': [
                    models.Index(fields=['user', 'rating', '-updated_at'], name='ai_qfb_user_rating_idx'),
                    models.Index(fields=['user', 'department', '-updated_at'], name='ai_qfb_user_dept_idx'),
                    models.Index(fields=['department', 'rating'], name='ai_qfb_dept_rating_idx'),
                ],
            },
        ),
    ]
