# Generated by Codex on 2026-05-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0101_aiworkspacequestionfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkspaceAnswerDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('department', '부서')], default='department', max_length=20, verbose_name='답변 범위')),
                ('direction', models.TextField(blank=True, default='', verbose_name='현재 답변 방향')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workspace_answer_directions', to='reporting.department', verbose_name='관련 부서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workspace_answer_directions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 현재 답변 방향',
                'verbose_name_plural': 'AI 현재 답변 방향 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIWorkspaceQuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all', '전체 부서'), ('department', '부서')], default='department', max_length=20, verbose_name='질문 범위')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='답변 스냅샷')),
                ('source', models.CharField(blank=True, default='', max_length=30, verbose_name='답변 출처')),
                ('model', models.CharField(blank=True, default='', max_length=60, verbose_name='선택 모델')),
                ('web_search_used', models.BooleanField(default=False, verbose_name='웹 검색 사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_workspace_question_logs', to='reporting.department', verbose_name='관련 부서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workspace_question_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 질문 답변 기록',
                'verbose_name_plural': 'AI 질문 답변 기록 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiworkspaceanswerdirection',
            index=models.Index(fields=['user', 'department'], name='ai_dir_user_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='aiworkspacequestionlog',
            index=models.Index(fields=['user', 'department', '-created_at'], name='ai_qlog_user_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='aiworkspacequestionlog',
            index=models.Index(fields=['user', '-created_at'], name='ai_qlog_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiworkspaceanswerdirection',
            constraint=models.UniqueConstraint(fields=('user', 'department', 'scope_type'), name='ai_answer_direction_unique'),
        ),
    ]
