# Generated by Django 5.2.3 on 2026-05-17 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0102_aiworkspaceanswerdirection_aiworkspacequestionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200, verbose_name='장비명')),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='모델명')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='시리얼번호')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='구매일')),
                ('install_location', models.CharField(blank=True, max_length=200, verbose_name='설치장소')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='보증 종료일')),
                ('status', models.CharField(choices=[('active', '사용중'), ('inactive', '미사용'), ('disposed', '폐기'), ('unknown', '미확인')], default='active', max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assets', to='reporting.company', verbose_name='업체/학교')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_assets', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assets', to='reporting.department', verbose_name='부서/연구실')),
                ('primary_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assets', to='reporting.followup', verbose_name='주 담당 고객')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assets', to='reporting.product', verbose_name='연결 제품')),
            ],
            options={
                'verbose_name': '고객 보유 장비',
                'verbose_name_plural': '고객 보유 장비 목록',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField(verbose_name='교정일')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='다음 교정 예정일')),
                ('result', models.CharField(choices=[('pass', '적합'), ('fail', '부적합'), ('adjusted', '조정 완료'), ('pending', '확인중')], default='pass', max_length=20, verbose_name='결과')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='calibration_certificates/%Y/%m/', verbose_name='교정 성적서')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calibration_records', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_records', to='reporting.followup', verbose_name='관련 고객')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_calibrations', to=settings.AUTH_USER_MODEL, verbose_name='교정 담당자')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='reporting.customerasset', verbose_name='장비')),
            ],
            options={
                'verbose_name': '교정 이력',
                'verbose_name_plural': '교정 이력 목록',
                'ordering': ['-calibration_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('service', 'A/S'), ('repair', '수리'), ('claim', '클레임'), ('exchange', '교환'), ('return', '반품'), ('inspection', '점검'), ('other', '기타')], default='service', max_length=30, verbose_name='케이스 유형')),
                ('status', models.CharField(choices=[('received', '접수'), ('in_progress', '진행중'), ('waiting', '대기'), ('completed', '완료'), ('cancelled', '취소')], default='received', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급')], default='normal', max_length=20, verbose_name='우선순위')),
                ('received_date', models.DateField(verbose_name='접수일')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='처리 예정일')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='완료일')),
                ('symptom', models.TextField(blank=True, verbose_name='증상/요청')),
                ('resolution', models.TextField(blank=True, verbose_name='처리 내용')),
                ('service_report', models.FileField(blank=True, null=True, upload_to='service_reports/%Y/%m/', verbose_name='서비스 리포트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cases', to='reporting.customerasset', verbose_name='장비')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_cases', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_cases', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cases', to='reporting.followup', verbose_name='관련 고객')),
            ],
            options={
                'verbose_name': '서비스 케이스',
                'verbose_name_plural': '서비스 케이스 목록',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerasset',
            index=models.Index(fields=['company', 'department'], name='asset_company_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='customerasset',
            index=models.Index(fields=['primary_followup', '-updated_at'], name='asset_followup_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='customerasset',
            index=models.Index(fields=['created_by', '-updated_at'], name='asset_creator_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='customerasset',
            index=models.Index(fields=['serial_number'], name='asset_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['asset', '-calibration_date'], name='cal_asset_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['followup', '-calibration_date'], name='cal_followup_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['next_due_date'], name='cal_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['created_by', '-calibration_date'], name='cal_creator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['asset', 'status'], name='svc_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['followup', '-received_date'], name='svc_followup_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['created_by', '-received_date'], name='svc_creator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['status', 'due_date'], name='svc_status_due_idx'),
        ),
    ]
