# Generated by Django 5.2.3 on 2026-05-18 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0103_customerasset_calibrationrecord_servicecase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail API'), ('imap', 'IMAP'), ('smtp', 'SMTP')], default='gmail', max_length=20, verbose_name='이메일 제공자')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='발신자 이메일')),
                ('to_email', models.EmailField(max_length=254, verbose_name='수신자 이메일')),
                ('cc_emails', models.TextField(blank=True, help_text='쉼표로 구분', verbose_name='참조 (CC)')),
                ('bcc_emails', models.TextField(blank=True, help_text='쉼표로 구분', verbose_name='숨은 참조 (BCC)')),
                ('subject', models.CharField(max_length=500, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML 본문')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='예약 발송 일시')),
                ('status', models.CharField(choices=[('pending', '예약 대기'), ('sending', '발송 중'), ('sent', '발송 완료'), ('failed', '발송 실패'), ('cancelled', '예약 취소')], db_index=True, default='pending', max_length=20, verbose_name='상태')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='발송 시도 횟수')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 시도 일시')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='실제 발송 일시')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='예약 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('business_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.businesscard', verbose_name='사용된 명함')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_emails', to='reporting.followup', verbose_name='관련 팔로우업')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_replies', to='reporting.emaillog', verbose_name='답장 대상 메일')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_emails', to='reporting.schedule', verbose_name='관련 일정')),
                ('sent_email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_source', to='reporting.emaillog', verbose_name='발송 완료 메일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to=settings.AUTH_USER_MODEL, verbose_name='예약자')),
            ],
            options={
                'verbose_name': '예약 메일',
                'verbose_name_plural': '예약 메일 목록',
                'ordering': ['scheduled_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scheduled_email_attachments/%Y/%m/', verbose_name='첨부 파일')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('mimetype', models.CharField(default='application/octet-stream', max_length=255, verbose_name='MIME 타입')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='파일 크기')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='첨부 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('scheduled_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reporting.scheduledemail', verbose_name='예약 메일')),
            ],
            options={
                'verbose_name': '예약 메일 첨부파일',
                'verbose_name_plural': '예약 메일 첨부파일 목록',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['status', 'scheduled_at'], name='reporting_s_status_c1c0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['user', 'status', 'scheduled_at'], name='reporting_s_user_id_1629c9_idx'),
        ),
    ]
