# Generated by Django 5.2.3 on 2026-05-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0104_scheduledemail_scheduledemailattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkspaceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all', '전체 부서'), ('department', '부서')], default='department', max_length=20, verbose_name='기억 범위')),
                ('memory_type', models.CharField(choices=[('fact', '검수 사실'), ('correction', '정정'), ('preference', '답변 선호')], default='fact', max_length=20, verbose_name='기억 유형')),
                ('title', models.CharField(blank=True, default='', max_length=180, verbose_name='제목')),
                ('content', models.TextField(verbose_name='검수 기억')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_workspace_memories', to='reporting.department', verbose_name='관련 부서')),
                ('source_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memories', to='reporting.aiworkspacequestionfeedback', verbose_name='출처 피드백')),
                ('source_question_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memories', to='reporting.aiworkspacequestionlog', verbose_name='출처 질문 기록')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workspace_memories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 검수 기억',
                'verbose_name_plural': 'AI 검수 기억 목록',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'department', 'is_active', '-updated_at'], name='ai_mem_user_dept_active_idx'), models.Index(fields=['user', 'scope_type', 'is_active', '-updated_at'], name='ai_mem_user_scope_active_idx'), models.Index(fields=['source_question_log'], name='ai_mem_source_qlog_idx')],
            },
        ),
    ]
