# Generated by Django 5.2.3 on 2026-05-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0105_aiworkspacememory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('customer_meeting', '고객 미팅'), ('quote', '견적'), ('delivery_schedule', '납품 일정'), ('service', '메모'), ('memo', '메모')], max_length=50, verbose_name='활동 유형'),
        ),
    ]
