# Generated by Django 5.2.3 on 2026-05-22 00:37

from django.db import migrations, models
from django.db.models import Q


def backfill_delivery_payment_type(apps, schema_editor):
    Schedule = apps.get_model('reporting', 'Schedule')
    PrepaymentUsage = apps.get_model('reporting', 'PrepaymentUsage')
    usage_schedule_ids = PrepaymentUsage.objects.filter(
        schedule_id__isnull=False,
    ).values_list('schedule_id', flat=True)

    Schedule.objects.filter(
        activity_type='delivery',
    ).filter(
        Q(use_prepayment=True)
        | Q(prepayment_id__isnull=False)
        | Q(prepayment_amount__gt=0)
        | Q(id__in=usage_schedule_ids)
    ).update(delivery_payment_type='prepayment_deduction')


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0106_alter_history_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='delivery_payment_type',
            field=models.CharField(choices=[('normal', '일반 납품'), ('prepayment_deduction', '선결제 차감 납품')], default='normal', help_text='납품 일정의 결제 구분입니다. 선결제 차감은 구조화된 선결제 사용 내역으로만 확정합니다.', max_length=32, verbose_name='납품 결제 구분'),
        ),
        migrations.RunPython(backfill_delivery_payment_type, migrations.RunPython.noop),
    ]
