# Generated by Django 5.2.3 on 2026-05-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0107_add_delivery_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCleanupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('department_merge', '부서/연구실 계정 병합'), ('contact_merge', '담당자 병합')], max_length=32, verbose_name='정리 유형')),
                ('mode', models.CharField(choices=[('dry_run', 'Dry-run'), ('execute', 'Execute')], default='dry_run', max_length=16, verbose_name='실행 모드')),
                ('confirmation_text', models.CharField(blank=True, max_length=255, verbose_name='확인 문구')),
                ('before_snapshot', models.JSONField(blank=True, default=dict, verbose_name='실행 전 스냅샷')),
                ('after_snapshot', models.JSONField(blank=True, default=dict, verbose_name='실행 후 스냅샷')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='실행 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_cleanup_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.department', verbose_name='원본 부서/연구실')),
                ('source_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.followup', verbose_name='원본 담당자')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.department', verbose_name='대상 부서/연구실')),
                ('target_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.followup', verbose_name='대상 담당자')),
            ],
            options={
                'verbose_name': '계정 정리 감사 로그',
                'verbose_name_plural': '계정 정리 감사 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'mode', '-created_at'], name='acct_cleanup_action_idx'), models.Index(fields=['source_department', 'target_department'], name='acct_cleanup_dept_idx'), models.Index(fields=['source_followup', 'target_followup'], name='acct_cleanup_contact_idx')],
            },
        ),
    ]
