# Generated by Django 5.2.3 on 2026-05-22 09:49

from django.db import migrations, models


def backfill_delivery_payment_status(apps, schema_editor):
    Schedule = apps.get_model('reporting', 'Schedule')
    PrepaymentUsage = apps.get_model('reporting', 'PrepaymentUsage')

    delivery_schedules = Schedule.objects.filter(activity_type='delivery')
    usage_schedule_ids = PrepaymentUsage.objects.filter(
        schedule_id__isnull=False,
    ).values_list('schedule_id', flat=True)

    delivery_schedules.filter(
        delivery_payment_type='prepayment_deduction',
    ).update(delivery_payment_status='prepayment_deduction')
    delivery_schedules.filter(
        use_prepayment=True,
    ).update(delivery_payment_status='prepayment_deduction')
    delivery_schedules.filter(
        prepayment_id__isnull=False,
    ).update(delivery_payment_status='prepayment_deduction')
    delivery_schedules.filter(
        prepayment_amount__gt=0,
    ).update(delivery_payment_status='prepayment_deduction')
    delivery_schedules.filter(
        id__in=usage_schedule_ids,
    ).update(delivery_payment_status='prepayment_deduction')
    delivery_schedules.filter(
        status='cancelled',
    ).update(delivery_payment_status='cancelled_returned')


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0108_accountcleanupauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='delivery_payment_status',
            field=models.CharField(choices=[('normal', '일반 납품'), ('prepayment_deduction', '선결제 차감 납품'), ('needs_review', '결제 확인 필요'), ('settled', '정산 완료'), ('cancelled_returned', '취소/반품')], default='normal', help_text='납품 일정의 결제 처리 상태입니다. 리포트, 엑셀, AI 답변이 이 구조화 필드를 우선 참조합니다.', max_length=32, verbose_name='납품 결제 상태'),
        ),
        migrations.RunPython(backfill_delivery_payment_status, migrations.RunPython.noop),
    ]
