# Generated by Django 5.2.3 on 2026-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0109_schedule_delivery_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.TextField(blank=True, verbose_name='계정 주소'),
        ),
        migrations.AddField(
            model_name='department',
            name='notes',
            field=models.TextField(blank=True, verbose_name='계정 메모'),
        ),
        migrations.AddField(
            model_name='followup',
            name='contact_role',
            field=models.CharField(choices=[('pi', 'PI'), ('practitioner', '실무자'), ('purchasing', '구매/행정 담당자'), ('tax_invoice', '세금계산서 담당자')], default='practitioner', max_length=20, verbose_name='담당자 역할'),
        ),
        migrations.AddField(
            model_name='followup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 담당자'),
        ),
    ]
