# Generated by Django 5.2.3 on 2026-05-22 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_prepayment_department(apps, schema_editor):
    Prepayment = apps.get_model('reporting', 'Prepayment')
    db_alias = schema_editor.connection.alias
    for prepayment_id, department_id in (
        Prepayment.objects.using(db_alias)
        .filter(department__isnull=True, customer_id__isnull=False)
        .values_list('id', 'customer__department_id')
        .iterator()
    ):
        if department_id:
            Prepayment.objects.using(db_alias).filter(pk=prepayment_id).update(department_id=department_id)


def backfill_prepayment_ledger_entries(apps, schema_editor):
    Prepayment = apps.get_model('reporting', 'Prepayment')
    PrepaymentUsage = apps.get_model('reporting', 'PrepaymentUsage')
    PrepaymentLedgerEntry = apps.get_model('reporting', 'PrepaymentLedgerEntry')
    db_alias = schema_editor.connection.alias

    entries = []
    for prepayment in Prepayment.objects.using(db_alias).all().iterator():
        entries.append(PrepaymentLedgerEntry(
            prepayment_id=prepayment.id,
            department_id=prepayment.department_id,
            customer_id=prepayment.customer_id,
            entry_type='deposit',
            amount=prepayment.amount or 0,
            balance_before=0,
            balance_after=prepayment.amount or 0,
            actor_id=prepayment.created_by_id,
            memo='기존 선결제 등록 기록 이관',
        ))
        if prepayment.status == 'cancelled':
            entries.append(PrepaymentLedgerEntry(
                prepayment_id=prepayment.id,
                department_id=prepayment.department_id,
                customer_id=prepayment.customer_id,
                entry_type='cancellation',
                amount=prepayment.balance or 0,
                balance_before=prepayment.balance or 0,
                balance_after=prepayment.balance or 0,
                actor_id=prepayment.created_by_id,
                memo=prepayment.cancel_reason or '기존 취소 기록 이관',
            ))

    for usage in PrepaymentUsage.objects.using(db_alias).select_related('prepayment').all().iterator():
        prepayment = usage.prepayment
        entries.append(PrepaymentLedgerEntry(
            prepayment_id=usage.prepayment_id,
            department_id=prepayment.department_id,
            customer_id=prepayment.customer_id,
            schedule_id=usage.schedule_id,
            usage_id=usage.id,
            entry_type='delivery_deduction',
            amount=usage.amount or 0,
            balance_after=usage.remaining_balance,
            actor_id=prepayment.created_by_id,
            memo=usage.memo or '기존 납품 차감 기록 이관',
        ))

    if entries:
        PrepaymentLedgerEntry.objects.using(db_alias).bulk_create(entries, batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0110_account_contact_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaymentLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', '등록'), ('delivery_deduction', '납품 차감'), ('adjustment', '조정'), ('transfer', '이관'), ('cancellation', '취소'), ('restore', '차감 복구'), ('deletion', '삭제')], max_length=32, verbose_name='이벤트 유형')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='금액')),
                ('balance_before', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='이전 잔액')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='이후 잔액')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
            ],
            options={
                'verbose_name': '선결제 원장 이벤트',
                'verbose_name_plural': '선결제 원장 이벤트 목록',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='prepayment',
            name='department',
            field=models.ForeignKey(blank=True, help_text='선결제를 소유하는 부서/연구실 계정입니다. 기존 담당자 연결은 호환용으로 유지합니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepayments', to='reporting.department', verbose_name='계정/부서'),
        ),
        migrations.RunPython(backfill_prepayment_department, noop_reverse),
        migrations.AddIndex(
            model_name='prepayment',
            index=models.Index(fields=['department', 'created_by', 'payment_date'], name='prepay_dept_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prepayment',
            index=models.Index(fields=['department', 'status'], name='prepay_dept_status_idx'),
        ),
        migrations.AddField(
            model_name='prepaymentledgerentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='처리자'),
        ),
        migrations.AddField(
            model_name='prepaymentledgerentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment_ledger_entries', to='reporting.followup', verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='prepaymentledgerentry',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment_ledger_entries', to='reporting.department', verbose_name='계정/부서'),
        ),
        migrations.AddField(
            model_name='prepaymentledgerentry',
            name='prepayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='reporting.prepayment', verbose_name='선결제'),
        ),
        migrations.AddField(
            model_name='prepaymentledgerentry',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment_ledger_entries', to='reporting.schedule', verbose_name='납품 일정'),
        ),
        migrations.AddField(
            model_name='prepaymentledgerentry',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_prepayment_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='대상 담당자'),
        ),
        migrations.AddField(
            model_name='prepaymentledgerentry',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='reporting.prepaymentusage', verbose_name='차감 내역'),
        ),
        migrations.RunPython(backfill_prepayment_ledger_entries, noop_reverse),
        migrations.AddIndex(
            model_name='prepaymentledgerentry',
            index=models.Index(fields=['prepayment', '-created_at'], name='prepay_log_prepay_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prepaymentledgerentry',
            index=models.Index(fields=['department', '-created_at'], name='prepay_log_dept_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prepaymentledgerentry',
            index=models.Index(fields=['actor', '-created_at'], name='prepay_log_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prepaymentledgerentry',
            index=models.Index(fields=['entry_type', '-created_at'], name='prepay_log_type_created_idx'),
        ),
    ]
