# Generated by Django 5.2.3 on 2026-05-22 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0111_prepaymentledgerentry_prepayment_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcleanupauditlog',
            name='action_type',
            field=models.CharField(choices=[('department_merge', '부서/연구실 계정 병합'), ('contact_merge', '담당자 병합'), ('contact_account_assign', '미지정 담당자 계정 지정')], max_length=32, verbose_name='정리 유형'),
        ),
        migrations.CreateModel(
            name='AccountCleanupDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_key', models.CharField(max_length=255, unique=True, verbose_name='후보 키')),
                ('candidate_type', models.CharField(choices=[('duplicate_account', '계정명 유사 후보'), ('duplicate_contact', '담당자 중복 후보'), ('unassigned_department', '부서 미지정 담당자'), ('unassigned_company', '업체 미지정 담당자')], max_length=40, verbose_name='후보 유형')),
                ('decision', models.CharField(choices=[('hold', '보류'), ('dismissed', '제외')], max_length=20, verbose_name='판단')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='후보 표시명')),
                ('reason', models.TextField(blank=True, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_cleanup_decisions', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.department', verbose_name='원본 부서/연구실')),
                ('source_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.followup', verbose_name='원본 담당자')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.department', verbose_name='대상 부서/연구실')),
                ('target_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.followup', verbose_name='대상 담당자')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_account_cleanup_decisions', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '계정 정리 후보 판단',
                'verbose_name_plural': '계정 정리 후보 판단',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['candidate_type', 'decision', '-updated_at'], name='acct_cleanup_decision_idx'), models.Index(fields=['source_department', 'target_department'], name='acct_cleanup_dec_dept_idx'), models.Index(fields=['source_followup', 'target_followup'], name='acct_cleanup_dec_contact_idx')],
            },
        ),
    ]
