# Generated by Django 5.2.3 on 2026-05-25 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0112_account_cleanup_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerasset',
            index=models.Index(fields=['created_by', 'status', '-updated_at', '-created_at'], name='asset_cr_status_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['user', '-updated_at', '-created_at'], name='follow_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'parent_history', 'next_action_date'], name='hist_user_parent_next_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['followup', 'parent_history', '-created_at'], name='hist_follow_parent_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prepayment',
            index=models.Index(fields=['created_by', 'status', '-payment_date', '-created_at'], name='prepay_user_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['followup', 'status', 'visit_date', 'visit_time'], name='sched_follow_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['asset', '-received_date', '-created_at'], name='svc_asset_received_created_idx'),
        ),
    ]
