# Generated by Django 5.2.3 on 2026-05-25 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0113_customerasset_asset_cr_status_upd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='card_payment_received',
            field=models.BooleanField(default=False, verbose_name='카드결제 확인'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='receivable_settled',
            field=models.BooleanField(default=False, verbose_name='외상 수금 완료'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='receivable_settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='외상 수금 완료일시'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='receivable_settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_settled_items', to=settings.AUTH_USER_MODEL, verbose_name='외상 수금 처리자'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['tax_invoice_issued', 'receivable_settled'], name='delivery_receivable_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['card_payment_received'], name='delivery_card_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['schedule', 'tax_invoice_issued'], name='delivery_sched_tax_idx'),
        ),
    ]
