# Generated by Django 5.2.3 on 2026-05-28 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_department_links(apps, schema_editor):
    History = apps.get_model('reporting', 'History')
    Schedule = apps.get_model('reporting', 'Schedule')

    histories = History.objects.filter(
        department__isnull=True,
        followup__department__isnull=False,
    ).values_list('id', 'followup__department_id')
    for history_id, department_id in histories.iterator():
        History.objects.filter(id=history_id, department__isnull=True).update(department_id=department_id)

    schedules = Schedule.objects.filter(
        department__isnull=True,
        followup__department__isnull=False,
    ).values_list('id', 'followup__department_id')
    for schedule_id, department_id in schedules.iterator():
        Schedule.objects.filter(id=schedule_id, department__isnull=True).update(department_id=department_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0114_deliveryitem_card_payment_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='reporting.department', verbose_name='관련 부서/연구실'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='reporting.department', verbose_name='관련 부서/연구실'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reporting.followup', verbose_name='관련 팔로우업'),
        ),
        migrations.RunPython(backfill_department_links, noop_reverse),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['department', 'parent_history', '-created_at'], name='hist_dept_parent_created_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['department', 'activity_type'], name='sched_dept_act_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['department', 'status', 'visit_date'], name='sched_dept_status_date_idx'),
        ),
    ]
