# Generated by Django 4.2.30 on 2026-06-01 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reporting", "0117_normalize_meeting_probability_to_five_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=200, verbose_name="제품명 백업"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="시리얼/식별번호"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="수량")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정"),
                            ("active", "진행중"),
                            ("returned", "회수완료"),
                            ("converted", "구매전환"),
                            ("cancelled", "취소"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "expected_return_date",
                    models.DateField(blank=True, null=True, verbose_name="반납 예정일"),
                ),
                (
                    "returned_date",
                    models.DateField(blank=True, null=True, verbose_name="회수일"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_records",
                        to="reporting.company",
                        verbose_name="업체/학교",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_demo_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_records",
                        to="reporting.department",
                        verbose_name="부서/연구실",
                    ),
                ),
                (
                    "followup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demo_records",
                        to="reporting.followup",
                        verbose_name="담당자/고객",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_demo_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demo_records",
                        to="reporting.product",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "데모 기록",
                "verbose_name_plural": "데모 기록 목록",
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_date"], name="demo_status_start_idx"
                    ),
                    models.Index(
                        fields=["department", "status"], name="demo_dept_status_idx"
                    ),
                    models.Index(
                        fields=["followup", "status"], name="demo_followup_status_idx"
                    ),
                    models.Index(
                        fields=["product", "status"], name="demo_product_status_idx"
                    ),
                    models.Index(
                        fields=["owner", "status"], name="demo_owner_status_idx"
                    ),
                ],
            },
        ),
    ]
