# Generated by Django 5.2.3 on 2026-06-02 07:34

from datetime import datetime, timezone
from django.db import migrations, models


def copy_quote_notes_to_option_description(apps, schema_editor):
    DeliveryItem = apps.get_model('reporting', 'DeliveryItem')
    # The first implementation temporarily stored quote option text in notes.
    # Preserve only items changed after that rollout instead of duplicating old remarks.
    rollout_cutoff = datetime(2026, 6, 2, 7, 0, tzinfo=timezone.utc)
    items = DeliveryItem.objects.filter(
        schedule__activity_type='quote',
        option_description__isnull=True,
        updated_at__gte=rollout_cutoff,
    ).exclude(notes__isnull=True).exclude(notes='')
    for item in items.iterator():
        item.option_description = item.notes
        item.save(update_fields=['option_description'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0118_demorecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='option_description',
            field=models.TextField(blank=True, null=True, verbose_name='옵션/별도 설명'),
        ),
        migrations.RunPython(copy_quote_notes_to_option_description, noop_reverse),
    ]
