# Generated by Django 5.2.3 on 2026-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0119_deliveryitem_option_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='pipeline_hidden',
            field=models.BooleanField(default=False, help_text='True이면 파이프라인 보드에서 카드를 숨김(데이터는 보존, 복원 가능)', verbose_name='파이프라인 숨김'),
        ),
    ]
