# Generated by Django 5.2.3 on 2026-07-31 02:02

from django.db import migrations, models


def mark_current_year_already_reset(apps, schema_editor):
    """올해는 이미 진행 중인 상태 그대로 유지한다 — 이 기능이 배포된 시점의
    파이프라인은 "이미 갈 데까지 간" 올해 데이터이지, 리셋 대상이 아니다.
    다음 리셋은 자연스럽게 내년 1월 1일에 처음 열람될 때 일어난다.
    """
    from django.utils import timezone

    PipelineYearResetLog = apps.get_model('reporting', 'PipelineYearResetLog')
    PipelineYearResetLog.objects.get_or_create(year=timezone.localdate().year)


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0122_backfill_won_stage_for_delivered_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineYearResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='연도')),
                ('reset_at', models.DateTimeField(auto_now_add=True, verbose_name='리셋 시각')),
                ('affected_count', models.PositiveIntegerField(default=0, verbose_name='리셋된 계정 수')),
            ],
            options={
                'verbose_name': '파이프라인 연간 리셋 기록',
                'verbose_name_plural': '파이프라인 연간 리셋 기록',
                'ordering': ['-year'],
            },
        ),
        migrations.RunPython(mark_current_year_already_reset, migrations.RunPython.noop),
    ]
