# Generated by Django 5.2.3 on 2026-08-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0123_pipeline_year_reset_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='pipeline_probability_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='설정하면 견적/일정 기반 자동 계산 확률보다 우선 적용됨(0~100)', null=True, verbose_name='파이프라인 확률 수동 입력'),
        ),
    ]
