# Generated by Django 5.2.3 on 2025-11-28 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0072_alter_documenttemplate_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='상세 내용')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('ongoing', '진행중'), ('on_hold', '보류'), ('done', '완료'), ('rejected', '반려')], default='ongoing', max_length=20, verbose_name='상태')),
                ('source_type', models.CharField(choices=[('self', '직접 생성'), ('ai_suggested', 'AI 추천'), ('peer_request', '동료 요청'), ('manager_assign', '매니저 하달')], default='self', max_length=20, verbose_name='출처')),
                ('expected_duration', models.IntegerField(blank=True, choices=[(15, '15분'), (30, '30분'), (60, '1시간'), (120, '2시간'), (240, '4시간'), (480, '하루')], null=True, verbose_name='예상 소요시간(분)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_todos', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_todos', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.followup', verbose_name='관련 고객')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_todos', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODO 목록',
                'db_table': 'todo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='todo_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todos.todo')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TODO 첨부파일',
                'verbose_name_plural': 'TODO 첨부파일',
                'db_table': 'todo_attachment',
            },
        ),
        migrations.CreateModel(
            name='TodoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', '생성'), ('updated', '수정'), ('status_changed', '상태 변경'), ('assigned', '담당자 지정'), ('approved', '승인'), ('rejected', '반려'), ('completed', '완료'), ('delegated', '업무 요청'), ('commented', '코멘트')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('prev_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='todos.todo')),
            ],
            options={
                'verbose_name': 'TODO 로그',
                'verbose_name_plural': 'TODO 로그',
                'db_table': 'todo_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['created_by', 'status'], name='todo_created_5c7989_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['assigned_to', 'status'], name='todo_assigne_7abd68_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['due_date'], name='todo_due_dat_740cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['source_type'], name='todo_source__7afaf7_idx'),
        ),
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['todo', 'created_at'], name='todo_log_todo_id_789fdd_idx'),
        ),
    ]
