# Generated by Django 5.2.3 on 2025-12-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expected_duration',
            field=models.IntegerField(blank=True, choices=[(15, '15분'), (30, '30분'), (60, '1시간'), (120, '2시간'), (240, '4시간 (반나절)'), (480, '1일'), (960, '2일'), (1440, '3일'), (2400, '1주일'), (4800, '2주일'), (9600, '1개월')], null=True, verbose_name='예상 소요시간(분)'),
        ),
    ]
